update functional-test module cargo jboss to use JDK6
To avoid exception being thrown when using JDK5 jboss
Statement.isClosed() and ResultSet.isClosed() method are since java 1.6. When using JDK5 jboss instance it will throw exception:
    java.lang.AbstractMethodError: org.jboss.resource.adapter.jdbc.jdk5.WrappedPreparedStatementJDK5.isClosed().

Also update that code to not call this method. Calling close() on an already closed ResultSet will be no-op. So won't matter.